### ISSUE TITLE
Platform error switch.tplink_router - Integration 'tplink_router' not found.

### ISSUE THREAD

**Issue by TomcatPi** [menahishayan/Home-Assistant-TP-Link-Router#14]
I try to use you custom integration in order to have access to my TP-Link archer C6, Intégration is installed, all the component seems to be here, but, when I add the switch to the configuration.yaml, i've got this error message

Platform error switch.tplink_router - Integration 'tplink_router' not found.

what I do wrong ?

**Comment by kuroki-kael** [comment]
Exactly the same here

**Comment by DanelRod** [comment]
same issue

**Comment by Fensterbrett** [comment]
same here

**Comment by 3shirts** [comment]
This seems to be to do with how it creates the folder structure. I found that by moving (actually copying) the subfolder "tplink_router" which is created in [HA FOLDER]/custom_components/Home-Assistant-TP-Link-Router/custom_components out to the main [HA FOLDER]/custom_components folder. That got me the switches. For some reason the sensors and device tracker didn't appear as entities and it the switches don't seem to support my Archer C7 router anyway.
