### ISSUE TITLE
AX50 Router help

### ISSUE THREAD

**Issue by microsby0** [menahishayan/Home-Assistant-TP-Link-Router#5]
I'm looking for help figuring out how to support the AX50 model. It does not appear to use a username so I'm not sure if it is supported by this integration. Any guidance or suggestions would be excellent. I've attempted to use `admin` as the username and found what I believe to be an access token returned by the `login?form=login` call. Its a cookie called `sysauth` but no luck. 

Additionally, when searching for this integration in HACS, the result that comes up is the [old](https://github.com/ericpignet/home-assistant-tplink_router) repository. Is this expected?

**Comment by menahishayan** [comment]
Hi, 

There is currently a thread open at the for this model [base repository](https://github.com/menahishayan/TP-Link-Archer-C50-API/issues/7), however, I just haven't been able to find the time to work on this project. You're welcome to look at the Readme and source, along with some of the other issues to make some progress towards your model.

But ideally, if the AX50 is supported by [ericpignet's repo](https://github.com/ericpignet/home-assistant-tplink_router) then it could also work with this repo with some modifications. 

Also, just to clarify, ericpignet's repo is not "the old repository". It was created and maintained by them and served as the inspiration for this project.

**Comment by microsby0** [comment]
Missed that issue! Thank you for the clarification, I'll close this issue and follow that one. I only referred to that repository as "old" because the last update was 2020 where as this repo has recent changes.
